### ISSUE TITLE
how to use the pre-trained model in word2vec

### ISSUE THREAD

**Issue by ezraguo-dev** [pdrm83/sent2vec#4]
Dear friend,

I'm a newcomer to NLP, and many thanks for your works to save a lot of time for me. But, for the word2vec sample on the GitHub page, I cannot find where the definition of PRETRAINED_VECTORS_PATH is. Could you explain more detailed to me?

Many thanks,

Ezra

**Comment by pdrm83** [comment]
You must first download a word2vec model from, for example, the [GloVe project](https://nlp.stanford.edu/projects/glove/). The PRETRAINED_VECTORS_PATH is the address of the corresponding file on your computer. Cheers

**Comment by pdrm83** [comment]
Did that response help you? If so please close the issue. Please also feel free to contribute to this open-source project.

**Comment by ezraguo-dev** [comment]
Great thanks for your suggestion, your response helps me alot

**Comment by rky71992** [comment]
Hello, I have seen your project and its very interesting. I am trying to implement it and receiving the same issue as mentioned above.
For PRETRAINED_VECTOR_PATH I have downloaded the pre-trained models from GloVe.(Wiki + Giga). Its a zip file containing 4 txt files. I have tried zip file path as well as txt file path. But its sill showing error.

Could you explain what I am doing wrong. Thanks
